# Globals
exclude: '^(.*/)?scratch\.py$'
repos:
  # Formatters
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        files: \.py$ # Target only Python files
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        files: \.py$ # Target only Python files
        args: ["--settings-path=pyproject.toml"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.14.0
    hooks:
      - id: yamlfmt
  # Linters
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        files: \.py$ # Target only Python files
        # Linter for Python code style and quality checks
        additional_dependencies: [flake8-pyproject]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.0
    hooks:
      - id: mypy
        additional_dependencies:
          - numpy
          - types-PyYAML
        args: ["--config-file=pyproject.toml"]
  # Miscellaneous
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        files: \.py$ # Target only Python files
